import factory from '@adonisjs/lucid/factories'
import Medication from '#models/medication'
import { MedicationForm } from '#models/medication'

const medications = [
  {
    name: 'Losartana Potássica',
    genericName: 'Losartana Potássica',
    description: 'Anti-hipertensivo',
    dosage: '50mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Anti-hipertensivo',
    minStock: 100,
    maxStock: 1000,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Metformina',
    genericName: 'Metformina',
    description: 'Antidiabético',
    dosage: '850mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Antidiabético',
    minStock: 100,
    maxStock: 1000,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Sertralina',
    genericName: 'Sertralina',
    description: 'Antidepressivo',
    dosage: '50mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Antidepressivo',
    minStock: 50,
    maxStock: 500,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Amitriptilina',
    genericName: 'Amitriptilina',
    description: 'Antidepressivo',
    dosage: '25mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Antidepressivo',
    minStock: 50,
    maxStock: 500,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Salbutamol',
    genericName: 'Salbutamol',
    description: 'Broncodilatador',
    dosage: '100mcg',
    form: MedicationForm.AEROSOL,
    category: 'Broncodilatador',
    minStock: 50,
    maxStock: 500,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Metotrexato',
    genericName: 'Metotrexato',
    description: 'Imunossupressor',
    dosage: '2,5mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Imunossupressor',
    minStock: 20,
    maxStock: 200,
    controlled: true,
    refrigerated: false,
  },
  {
    name: 'Levotiroxina',
    genericName: 'Levotiroxina',
    description: 'Hormônio tireoidiano',
    dosage: '50mcg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Hormônio',
    minStock: 100,
    maxStock: 1000,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Omeprazol',
    genericName: 'Omeprazol',
    description: 'Inibidor de bomba de prótons',
    dosage: '20mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Antiácido',
    minStock: 100,
    maxStock: 1000,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Sumatriptana',
    genericName: 'Sumatriptana',
    description: 'Antimigranoso',
    dosage: '50mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Antimigranoso',
    minStock: 50,
    maxStock: 500,
    controlled: false,
    refrigerated: false,
  },
  {
    name: 'Zolpidem',
    genericName: 'Zolpidem',
    description: 'Hipnótico',
    dosage: '10mg',
    form: MedicationForm.COMPRIMIDO,
    category: 'Hipnótico',
    minStock: 50,
    maxStock: 500,
    controlled: true,
    refrigerated: false,
  },
]

export const MedicationFactory = factory
  .define(Medication, async ({ faker }) => {
    const medication = faker.helpers.arrayElement(medications)
    return {
      ...medication,
      barcode: faker.number.int({ min: 100000000000, max: 999999999999 }).toString(),
    }
  })
  .build()
